### ISSUE TITLE
Error with Firefox 4

### ISSUE THREAD

**Issue by sjl** [fivesixty/notepages#1]
Hitting the home page with Firefox 4 seems to create the new page and redirect me to it, but the editing view doesn't show up.  There's an error visible in the Firebug console:

```
uncaught exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMNSHTMLTextAreaElement.selectionEnd]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: http://notepag.es/assets/lib/fieldSelection.jquery.js :: <TOP_LEVEL> :: line 22" data: no]
```

**Comment by c-spencer** [comment]
This commit:

https://github.com/fivesixty/notepages/commit/f13f88ce197e4c5b7e6ce6a9e9bc059a39ea9736

Should fix this on Firefox 4, where it seems exceptions are thrown if no selection is made.
