### ISSUE TITLE
support for markdown syntax for tables

### ISSUE THREAD

**Issue by gcapiel** [fivesixty/notepages#2]
support for markdown syntax for tables:

per http://michelf.com/projects/php-markdown/extra/#table

Example:
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell

**Comment by c-spencer** [comment]
I'll look into porting the extra features of that library to javascript.

For now, I'll submit a patch that allows table HTML to be used.
- Demonstration: http://notepag.es/tables
- Patch: e115ced454bbc7d367af509f35850d85ab26938e

**Comment by c-spencer** [comment]
Closing this as now supporting PHP Markdown Extra table syntax.

**Comment by gcapiel** [comment]
That was quick. It works great!

**Comment by gcapiel** [comment]
By the way, I mentioned your product to the MathJax team and they posted a link to it: http://www.mathjax.org/community/mathjax-in-use/
