### ISSUE TITLE
notepag.es Down

### ISSUE THREAD

**Issue by Dakta** [fivesixty/notepages#23]
As of the creation of this issue, http://notepag.es/ is down. All pages return err 502:

```
502 Bad Gateway
nginx/0.7.65
```

I assume this is a server configuration change, and not you abandoning the project. I'd be very happy to see the site back online. If not, and you're abandoning it for whatever reason, please drop me a line, at the very least I'd like to get a couple of my own documents off; I might even be interested in continuing hosting the project.

As a side note, it's a fantastic site. Props.

**Comment by c-spencer** [comment]
Bit of bad logic crashed it, it's now restarted. I'll be rewriting the server soonish I think, as it's rather hacked together.

**Comment by jvalanen** [comment]
This issue has appeared again...
