### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by lyoshenka** [fivesixty/notepages#24]
Hey, is the notepag.es site ever coming back? I'm looking for a doc I wrote about 7 months ago that I'd really like to get back, but it looks like the site has been down for a while now. I know I probably should have backed up the doc elsewhere, but if you could put the site back up even for a short while, I'd be very grateful.

Thanks.

**Comment by c-spencer** [comment]
Hi, I just resurrected it, I forgot to restart everything properly after moving a linode. Hopefully you'll find the document you're looking for.

**Comment by lyoshenka** [comment]
Thanks.
