### ISSUE TITLE
Is there a backup of the notepag.es database?

### ISSUE THREAD

**Issue by ghost** [fivesixty/notepages#25]
I wrote many documents on notepag.es about 1 year ago, and it seems like the website is not up now. Unfortunately, I'm not sure if I backed up those articles, and even if I did, I cannot find them now.

Is there any chance that you still have a database dump from which I might be able to extract the articles? I have the relevant links to notepag.es URLs, if that might help. I would highly appreciate if that might be possible. Thanks!

**Comment by c-spencer** [comment]
Hi, I've kicked the server into life again, hopefully everything should be where you wrote it. I don't maintain this any more, although I may return to it in future, if only to rewrite the tiny server part to be more reliable.

**Comment by ghost** [comment]
Thanks so much! I'll copy my documents right away. BTW, if you don't plan to maintain the server, you might want to leave a note somwhere, redirecting people looking for such an online writing platform to alternatives. FWIW, I quite liked notepag.es, though I haven't used it for over a year. These days, I use [StackEdit](https://stackedit.io/) which also seems quite nice, and lets you sync documents with Google Drive or Dropbox.

**Comment by c-spencer** [comment]
Yeah, quite a few nice alternatives cropped up since I wrote this. StackEdit is very nice, especially the scroll-syncing. I'll maybe tweak it to be read-only with some forward links.
